options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Deploy slack-webhook-handler Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-slack-webhook-handler'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack-webhook-handler'  # Function name
      - '--region=us-central1'
      - '--source=.'  # Path to the source code for slack-webhook-handler
      - '--runtime=python310'  # Python runtime for the function
      - '--entry-point=slack_webhook_handler'  # Function entry point
      - '--trigger-http'  # HTTP trigger
      - '--allow-unauthenticated'  # Allow unauthenticated access
    waitFor: ['-']  # Don't wait for any previous steps

  # Deploy slack-events Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-slack-events'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack-events'  # Function name
      - '--region=us-central1'
      - '--source=.'  # Path to the source code for slack-events
      - '--runtime=python310'  # Python runtime for the function
      - '--entry-point=slack_event_processor'  # Function entry point
      - '--trigger-http'  # HTTP trigger
      - '--allow-unauthenticated'  # Allow unauthenticated access
    waitFor: ['-']  # Don't wait for any previous steps
