steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - slack-event-processor
  - --gen2
  - --region=us-central1
  - --runtime=python310
  - --source=slack_events
  - --entry-point=slack_event_processor
  - --trigger-http
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY