options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_WEBHOOK_HANDLER: "false"

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-webhook-handler'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$_DEPLOY_WEBHOOK_HANDLER" == "true" ]]; then
          gcloud run deploy slack-webhook-handler \
            --source=./slack_webhook_handler \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated;
        else
          echo "Skipping slack-webhook-handler deployment.";
        fi
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-event-processor'
    args:
      - 'run'
      - 'deploy'
      - 'slack-events'
      - '--source'
      - './slack_event_processor'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['-']
