options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only for build logs

steps:
  # Step 1: Deploy the slack-webhook-handler function (Cloud Function)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-slack-webhook-handler'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack-webhook-handler'  # Name of the function
      - '--region=us-central1'  # Specify the region for deployment
      - '--source=slack_webhook_handler'  # Path to the function source
      - '--trigger-http'  # HTTP trigger for the function
      - '--runtime=python310'  # Python 3.10 runtime
      - '--entry-point=slack_webhook_handler'  # Entry point function name
      - '--allow-unauthenticated'  # Allow unauthenticated access
      - '--gen2'  # Explicitly deploy as Gen 2 function

  # Step 2: Deploy the slack-events function (Cloud Function)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-event-processor'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack-events'  # Name of the function
      - '--region=us-central1'  # Specify the region
      - '--source=./slack_events'  # Path to the function source
      - '--trigger-http'  # HTTP trigger
      - '--runtime=python310'  # Python 3.10 runtime
      - '--entry-point=slack_event_processor'  # Entry point function name
      - '--allow-unauthenticated'  # Allow unauthenticated access
      - '--gen2'  # Explicitly deploy as Gen 2 function
