options:
  logging: CLOUD_LOGGING_ONLY

# Deploy slack_events Cloud Function
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-event-processor'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack_events'  # Function name (matches the ID in your config)
      - '--region=us-central1'
      - '--source=.'  
      - '--trigger-http'
      - '--runtime=python310'
      - '--entry-point=slack_event_processor'  # Points to your main function
      - '--allow-unauthenticated'