options:
  logging: CLOUD_LOGGING_ONLY  # This tells Cloud Build to use Cloud Logging

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'slack-events'
      - '--region=us-central1'
      - '--source=slack_events'
      - '--trigger-http'
      - '--runtime=python310'
      - '--entry-point=slack_event_processor'
      - '--allow-unauthenticated'
