options:
  logging: CLOUD_LOGGING_ONLY

# Dynamic substitution variables
substitutions:
  _DEPLOY_WEBHOOK_HANDLER: "false"  # Set to "true" to deploy webhook handler
  
steps:
  # Conditional step that only runs when _DEPLOY_WEBHOOK_HANDLER is "true"
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-webhook-handler'
    args:
      - 'run'
      - 'deploy'
      - 'slack-webhook-handler'  
      - '--source'
      - './slack_webhook_handler'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    env:
      - 'SKIP=$(_DEPLOY_WEBHOOK_HANDLER!=true)'
    waitFor: ['-']  # Don't wait for any previous steps

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-event-processor'
    args:
      - 'run'
      - 'deploy'
      - 'slack-event-processor'  # Using the name from your original YAML
      - '--source'
      - './slack_events'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['-']  # Don't wait for any previous steps