options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-webhook-handler'
    args:
      - 'run'
      - 'deploy'
      - 'slack-webhook-handler'  
      - '--source'
      - './slack_webhook_handler'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['-']  # Don't wait for any previous steps

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-event-processor'
    args:
      - 'run'
      - 'deploy'
      - 'slack-event-processor'  # Using the name from your original YAML
      - '--source'
      - './slack_events'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['-']  # Don't wait for any previous steps