options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only for build logs

steps:
  # Step 1: Deploy slack-webhook-handler function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - slack-webhook-handler
      - --region=us-central1
      - --source=slack_webhook_handler
      - --trigger-http
      - --runtime=python310
      - --entry-point=slack_webhook_handler

  # Step 2: Deploy slack-events function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - slack-events
      - --region=us-central1
      - --source=slack_events
      - --trigger-http
      - --runtime=python310
      - --entry-point=slack_event_processor
